export const ALL_DOCUMENTS_SUCCESS = 'ALL_DOCUMENTS_SUCCESS';
export const POST_DOCUMENTS_SUCCESS = 'POST_DOCUMENTS_SUCCESS';
export const UPDATE_DOCUMENTS_SUCCESS = 'UPDATE_DOCUMENTS_SUCCESS';
export const DELETE_DOCUMENTS_SUCCESS = "DELETE_DOCUMENTS_SUCCESS";
export const SEARCH_DOCUMENTS_SUCCESS = "SEARCH_DOCUMENTS_SUCCESS";

export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const POST_USERS_SUCCESS = 'POST_USERS_SUCCESS';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_USER = 'SIGNUP_USER';

