export const ALL_DOCUMENTS_SUCCESS = 'ALL_DOCUMENTS_SUCCESS';
export const POST_DOCUMENTS_SUCCESS = 'POST_DOCUMENTS_SUCCESS';
export const UPDATE_DOCUMENTS_SUCCESS = 'UPDATE_DOCUMENTS_SUCCESS';
export const DELETE_DOCUMENTS_SUCCESS = "DELETE_DOCUMENTS_SUCCESS";
