export const ALL_DOCUMENTS_SUCCESS = 'ALL_DOCUMENTS_SUCCESS';
export const POST_DOCUMENTS_SUCCESS = 'POST_DOCUMENTS_SUCCESS';
export const UPDATE_DOCUMENTS_SUCCESS = 'UPDATE_DOCUMENTS_SUCCESS';
export const DELETE_DOCUMENTS_SUCCESS = "DELETE_DOCUMENTS_SUCCESS";
export const SEARCH_DOCUMENTS_SUCCESS = "SEARCH_DOCUMENTS_SUCCESS";
export const PUBLIC_DOCUMENTS_SUCCESS = 'PUBLIC_DOCUMENTS_SUCCESS';
export const PAGINATE_DOCUMENTS_SUCCESS = 'PAGINATE_DOCUMENTS_SUCCESS';

export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const POST_USERS_SUCCESS = 'POST_USERS_SUCCESS';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const PAGINATE_USERS_SUCCESS = 'PAGINATE_USERS_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGOUT_SUCCESS= 'LOGOUT_SUCCESS';

export const ALL_ROLES_SUCCESS = 'ALL_ROLES_SUCCESS';
export const POST_ROLE_SUCCESS = 'POST_ROLE_SUCCESS';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const SEARCH_ROLE_SUCCESS = 'SEARCH_ROLE_SUCCESS';
export const PAGINATE_ROLES_SUCCESS = 'PAGINATE_ROLES_SUCCESS';
